### ISSUE TITLE
Error when Source & Global Install

### ISSUE THREAD

**Issue by dwisiswant0** [FlameOfIgnis/puff#4]
Hi, I got error this error messages when try to install via `sudo npm install -g puff-fuzz`.

```
ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/lib/helper.js:94:19)
    at fetchBinary (/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/install.js:148:8)
    at download (/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/install.js:54:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/.local-chromium'
}
```

That's error shown even as root.

When I try to install by `npm install`. I got this:
`npm WARN puff-fuzz@0.0.4 No repository field.`

```
Environment:
16.04.1-Ubuntu
node v13.6.0
npm 6.13.4
```

Regards.

**Comment by ignis-sec** [comment]
Hello! You are getting `errno: 13 EACCESS`, because your user lacks the required permissions to write to directory `/usr/local/lib/node_modules/*`

Running the install with sudo should help. Please let me know if you get any other issues after that.

Cheers!

**Comment by ignis-sec** [comment]
> That's error shown even as root.

My bad, i just realised you are running as root. Could you quickly verify  that `/usr/local/lib/node_modules/puff-fuzz/ exists?


> When I try to install by npm install. I got this:
> npm WARN puff-fuzz@0.0.4 No repository field.

That warning should not be a problem, however `npm install` will not add the bash wrapper for the tool. You can still find the repository under `~/node_modules/puff-fuzz/`

I'll look into the EACCESS error and let you know if i can find the problem!

**Comment by dwisiswant0** [comment]
Aight, an error still occurs even when I create the directory manually by `mkdir -p /usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/.local-chromium`.

It's tricky, after I created the manual directory and ran `npm install -g puff-fuzz`, an error still occurred _(as above)_ & the directory that I created manually was deleted automatically.

Thoughts?

**Comment by ignis-sec** [comment]
Hmmm, i still don't understand what is causing the issue, but maybe setting the `PUPPETEER_SKIP_DOWNLOAD=true` flag in environment variables will solve the issue.

This will prevent puppeteer from installing chromium, that looks like the part with permissions issue.

You'll have to manually install a copy of chromium and set the chromium path via `puff -c /path/to/chromium`


**Another option** - i've been checking puppeteer issues since this is caused by puppeteer. I've found[ a similar issue](https://github.com/puppeteer/puppeteer/issues/367) suggesting `sudo npm install -g puppeteer --unsafe-perm=true`

You might want to try this one first.

Let me know about the result!

**Comment by dwisiswant0** [comment]
Resolved by `export PUPPETEER_SKIP_DOWNLOAD=true`. But still don't know why can't install `puppeteer` via `npm`.
